import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import LeftFloatingActionButtons from "./components/LeftFloatingActionButtons";
import RightFloatingActionButtons from "./components/RightFloatingActionButtons";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "LinkW Innovation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={`bg-slate-950 ${geistSans.variable} ${geistMono.variable} antialiased`}>
    
        <header>
          <Navbar /> {/* Navbar component */}
        </header>

        <main className="min-h-screen">{children}</main> {/* Main content area */}
        <LeftFloatingActionButtons />
				<RightFloatingActionButtons />
        <Footer /> {/* Footer component */}
      </body>
    </html>
  );
}
